name: _always skipped
on:
  pull_request:

jobs:
  first:
    name: first
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
  second:
    name: second
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
