name: _always skipped
on:
  pull_request:

jobs:
  first:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
  second:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
