name: skip test
on:
  pull_request:
    branchs:
      - feature/skip-test1

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
  second:
    needs: first
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
