name: skip test
on:
  pull_request:
    paths:
      - '.github/workflows/dummy.yml'

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
  second:
    needs: first
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
