name: skip test
on:
  pull_request:

jobs:
  first:
    name: first
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
  second:
    name: second
    needs: first
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
